# Generated by Django 3.1.4 on 2020-12-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=16)),
                ('profile', models.TextField(default='not edit yet')),
                ('like_users', models.CharField(max_length=512, null=True)),
                ('like_tags', models.CharField(max_length=512, null=True)),
                ('public', models.BooleanField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dis_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(db_index=True, max_length=128)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creater', models.CharField(db_index=True, max_length=16)),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('information', models.TextField()),
                ('tag_list', models.CharField(max_length=512)),
                ('recommend', models.IntegerField(default=0)),
                ('reply', models.TextField(default='There is no reply')),
                ('reply_number', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('last_reply', models.CharField(max_length=512, null=True)),
                ('last_name', models.CharField(max_length=16, null=True)),
                ('last_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Normal_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=16)),
                ('profile', models.TextField(default='not edit yet')),
                ('like_users', models.CharField(max_length=512, null=True)),
                ('like_tags', models.CharField(max_length=512, null=True)),
                ('public', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('information', models.TextField(default='Please edit by yourselves')),
                ('authors', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='paper_file/')),
                ('tag_list', models.CharField(max_length=512)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('last_edit_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
