# Generated by Django 3.1.4 on 2020-12-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(db_index=True, max_length=128, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('dis_list', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(db_index=True, max_length=16)),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('tag_list', models.JSONField(default=list)),
                ('paper_list', models.JSONField(default=list)),
                ('reply', models.JSONField(default=list)),
                ('reply_number', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('last', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('pubyear', models.CharField(default='unknown', max_length=10)),
                ('publisher', models.JSONField(default=list)),
                ('information', models.TextField(default='Please edit by yourselves')),
                ('admins', models.JSONField(default=list)),
                ('file', models.URLField(default='/media/file/LFS.pdf')),
                ('tag_list', models.JSONField(default=list)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('last_name', models.CharField(max_length=16, null=True)),
                ('last_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password_hash', models.CharField(max_length=16)),
                ('profile', models.TextField(default='not edit yet')),
                ('like_users', models.JSONField(default=list)),
                ('like_tags', models.JSONField(default=list)),
                ('is_admin', models.BooleanField(default=0)),
                ('public', models.BooleanField(default=1)),
            ],
        ),
    ]
