# Generated by Django 3.1.4 on 2020-12-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password_hash', models.CharField(max_length=16)),
                ('profile', models.TextField(default='not edit yet')),
                ('like_users', models.JSONField(default=[])),
                ('like_tags', models.JSONField(default=[])),
                ('is_admin', models.BooleanField(default=0)),
                ('public', models.BooleanField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin_user',
        ),
        migrations.DeleteModel(
            name='Normal_user',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='tag_list',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='papers',
            name='authors',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='papers',
            name='tag_list',
            field=models.JSONField(default=[]),
        ),
    ]
