# Generated by Django 3.1.4 on 2020-12-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
