# Generated by Django 3.1.4 on 2020-12-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_auto_20201210_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='tag_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='papers',
            name='authors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='papers',
            name='tag_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_users',
            field=models.JSONField(default=list),
        ),
    ]
