# Generated by Django 3.1.4 on 2020-12-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_discussion_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='file',
            field=models.URLField(default='file\\LFS.pdf'),
        ),
    ]
