# Generated by Django 3.1.4 on 2020-12-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0003_auto_20201210_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dis_center',
            new_name='DisCenter',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='creater',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='discussion',
            name='reco_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='information',
            field=models.TextField(default='I wanna say something'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='reply',
            field=models.JSONField(default=list),
        ),
    ]
