# Generated by Django 3.1.4 on 2020-12-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0004_auto_20201214_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='title',
            new_name='tittle',
        ),
    ]
