# Generated by Django 3.1.4 on 2020-12-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0005_auto_20201214_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discenter',
            name='tag_title',
        ),
        migrations.AddField(
            model_name='discenter',
            name='tag_tittle',
            field=models.CharField(db_index=True, default='abc', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='discenter',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
