# Generated by Django 3.1.4 on 2020-12-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0006_auto_20201214_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discenter',
            name='tag_tittle',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
