# Generated by Django 3.1.4 on 2020-12-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0007_auto_20201214_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papers',
            old_name='last_edit_time',
            new_name='last_time',
        ),
        migrations.AddField(
            model_name='papers',
            name='last_name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='file',
            field=models.FileField(default='file/LFS.pdf', upload_to='file/'),
        ),
    ]
