# Generated by Django 3.1.4 on 2020-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0008_auto_20201215_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='last_reply',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='last_time',
        ),
        migrations.AddField(
            model_name='discussion',
            name='last',
            field=models.JSONField(default=dict),
        ),
    ]
