# Generated by Django 3.1.4 on 2020-12-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0009_auto_20201215_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='file',
            field=models.URLField(default='/media/file/LFS.pdf'),
        ),
    ]
