# Generated by Django 3.1.4 on 2020-12-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0010_auto_20201215_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='information',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='reco_list',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='recommend',
        ),
    ]
