# Generated by Django 3.1.4 on 2020-12-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0011_auto_20201217_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discenter',
            name='tag_title',
            field=models.CharField(db_index=True, default='', max_length=128, unique=True),
        ),
    ]
