# Generated by Django 3.1.4 on 2020-12-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0012_auto_20201217_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='discenter',
            name='dis_list',
            field=models.JSONField(default=list),
        ),
    ]
